import { useState, useEffect } from 'react'
import { useWallet } from '@solana/wallet-adapter-react'
import { MessageSquare, Share2, Copy, Check } from 'lucide-react'
import { generateRoast } from '../lib/openai'
import AutonomousAlphaUpsell from './AutonomousAlphaUpsell'
import BotServiceUpsell from './BotServiceUpsell'

interface Roast {
  id: string
  text: string
  sentiment: 'positive' | 'negative' | 'neutral'
  created_at: string
}

export default function RoastDisplay() {
  const { publicKey, connected } = useWallet()
  const [loading, setLoading] = useState(false)
  const [roast, setRoast] = useState<Roast | null>(null)
  const [roastCount, setRoastCount] = useState(0)
  const [copied, setCopied] = useState(false)

  const generateRoastData = async () => {
    if (!publicKey) return

    setLoading(true)

    try {
      // For now, use mock wallet stats
      // TODO: Fetch real wallet stats from PortfolioCard component
      const mockWalletStats = {
        winRate: 34.0,
        totalProfit: 1250.50,
        totalLoss: 2340.75,
        degenScore: 78,
        totalTrades: 47,
        gasSpent: 142.30,
        topToken: 'BONK'
      }

      const roastResult = await generateRoast({
        walletStats: mockWalletStats,
        roastType: 'portfolio'
      })

      setRoast({
        id: Date.now().toString(),
        text: roastResult.text,
        sentiment: roastResult.sentiment,
        created_at: new Date().toISOString()
      })

      setRoastCount(prev => prev + 1)
    } catch (err) {
      console.error('Failed to generate roast:', err)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (connected && publicKey) {
      generateRoastData()
    }
  }, [connected, publicKey])

  const copyToClipboard = () => {
    if (roast?.text) {
      navigator.clipboard.writeText(`${roast.text} - Generated by AIBRO 🤖 https://aibro.io`)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const shareToTwitter = () => {
    if (roast?.text) {
      const text = encodeURIComponent(`${roast.text}\n\nGenerated by Agentic Bro 🤖\nhttps://agenticbro.io\n#AGNTCBRO #Solana #Crypto`)
      window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank')
    }
  }

  if (!connected) {
    return null
  }

  return (
    <div className="bg-black/40 backdrop-blur-md rounded-2xl p-6 border border-purple-500/20 animate-slide-in">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <span>💬</span> AI Roast
        </h2>
        <button
          onClick={generateRoastData}
          disabled={loading}
          className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-semibold transition-colors disabled:opacity-50 flex items-center gap-2"
        >
          {loading ? (
            <>
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating...
            </>
          ) : (
            <>
              <MessageSquare className="w-4 h-4" />
              New Roast
            </>
          )}
        </button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <div className="text-center">
            <div className="text-6xl mb-4">🤖💭</div>
            <p className="text-gray-400">AIBRO is analyzing your wallet...</p>
            <p className="text-sm text-gray-500 mt-2">This might hurt 💀</p>
          </div>
        </div>
      ) : roast ? (
        <div className="space-y-4">
          <div className="bg-gradient-to-br from-purple-900/30 to-pink-900/30 p-6 rounded-xl border border-purple-500/30 animate-pulse-glow">
            <p className="text-lg text-white leading-relaxed">{roast.text}</p>
          </div>

          <div className="flex gap-3">
            <button
              onClick={copyToClipboard}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-black/30 hover:bg-black/50 border border-gray-700 rounded-lg transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-green-400" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 text-gray-400" />
                  Copy
                </>
              )}
            </button>
            <button
              onClick={shareToTwitter}
              className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-[#1DA1F2] hover:bg-[#1a8cd8] text-white rounded-lg transition-colors font-semibold"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
          </div>

          <div className="text-center">
            <p className="text-sm text-gray-500">
              Powered by Agentic AI • 100% brutal honesty • No feelings spared
            </p>
          </div>

          {/* AutonomousAlpha Upsell */}
          <AutonomousAlphaUpsell />

          {/* Bot Service Upsell - Show after 3 roasts */}
          {roastCount >= 3 && <BotServiceUpsell />}
        </div>
      ) : null}
    </div>
  )
}