# Copyright (c) 2026 Agentic Bro. Licensed under the Business Source License 1.1.
# See LICENSE file in this directory. Change Date: 2029-05-24. Change License: Apache-2.0.
# Commercial use restrictions apply — contact agenticbro@agenticbro.app for licensing.

#!/usr/bin/env python3
"""
Alert Service — Brand Guard by Jeeevs / AgenticBro
====================================================
Generates alert notifications when new threats are detected.
Supports email alerts (via Resend/SendGrid) and in-app notifications.
Can be called from cron jobs or scan completion callbacks.

Usage:
  python3 alert-service.py --brand "Agentic Bro" --handle agenticbro --threat-type impersonator --severity high --target "@agenticbro_support" --evidence "Handle similarity 65%, impersonator_suffix"
  python3 alert-service.py --brand "Agentic Bro" --handle agenticbro --threat-type domain_lookalike --severity critical --target "loginagenticbro.app" --json
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional


# ── Alert severity thresholds ──────────────────────────────────────────────
SEVERITY_LEVELS = {
    'critical': {
        'emoji': '🚨',
        'subject_prefix': '[URGENT]',
        'priority': 1,
        'description': 'Immediate action required — active threat detected',
    },
    'high': {
        'emoji': '⚠️',
        'subject_prefix': '[ACTION NEEDED]',
        'priority': 2,
        'description': 'High-risk threat detected — review within 24 hours',
    },
    'medium': {
        'emoji': 'ℹ️',
        'subject_prefix': '[REVIEW]',
        'priority': 3,
        'description': 'Moderate risk detected — review within 48 hours',
    },
    'low': {
        'emoji': '✅',
        'subject_prefix': '[INFO]',
        'priority': 4,
        'description': 'Low-risk item detected — add to monitoring',
    },
}

THREAT_TYPE_LABELS = {
    'impersonator': 'Brand Impersonator Detected',
    'domain_lookalike': 'Domain Lookalike Detected',
    'phone_scam': 'Vendor Impersonation Scam',
    'cross_channel': 'Cross-Channel Threat Correlation',
    'scammer_db': 'Known Scammer Match',
    'resolved': 'Threat Resolved',
}


def generate_alert(
    brand_name: str,
    brand_handle: str,
    threat_type: str,
    severity: str,
    target: str,
    evidence: List[str],
    risk_score: float = 0,
    risk_level: str = 'MEDIUM',
    platform: str = 'unknown',
    takedown_url: str = '',
    dashboard_url: str = '',
) -> Dict[str, Any]:
    """Generate a complete alert notification."""
    severity_info = SEVERITY_LEVELS.get(severity.lower(), SEVERITY_LEVELS['medium'])
    threat_label = THREAT_TYPE_LABELS.get(threat_type, 'Threat Detected')
    
    # Build email subject
    subject = f"{severity_info['subject_prefix']} {threat_label}: {target} — {brand_name}"
    
    # Build email body
    body_lines = [
        f"{severity_info['emoji']} {threat_label}",
        f"",
        f"Brand: {brand_name} (@{brand_handle})",
        f"Threat: {target}",
        f"Platform: {platform.title()}",
        f"Severity: {severity.upper()}",
        f"Risk Score: {risk_score}/10 ({risk_level})",
        f"",
        f"Evidence:",
    ]
    for i, e in enumerate(evidence[:5], 1):
        body_lines.append(f"  {i}. {e}")
    
    body_lines.extend([
        f"",
        f"Recommended Action:",
    ])
    
    if severity in ['critical', 'high']:
        body_lines.extend([
            f"  → File an abuse report immediately",
            f"  → Review takedown templates in the Brand Guard dashboard",
        ])
    else:
        body_lines.extend([
            f"  → Add to monitoring schedule",
            f"  → Review in weekly threat digest",
        ])
    
    if takedown_url:
        body_lines.append(f"  → File takedown: {takedown_url}")
    if dashboard_url:
        body_lines.append(f"  → View dashboard: {dashboard_url}")
    
    body_lines.extend([
        f"",
        f"Generated by Brand Guard by Jeeevs / AgenticBro",
        f"Scan first, trust later! 🔐",
    ])
    
    body = '\n'.join(body_lines)
    
    # Build HTML email body
    severity_colors = {
        'critical': '#dc2626',
        'high': '#ea580c',
        'medium': '#ca8a04',
        'low': '#16a34a',
    }
    color = severity_colors.get(severity.lower(), '#6b7280')
    
    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
    <div style="background-color: {color}; color: white; padding: 16px 24px;">
      <h2 style="margin: 0; font-size: 18px;">{severity_info['emoji']} {threat_label}</h2>
      <p style="margin: 4px 0 0; font-size: 14px; opacity: 0.9;">{severity_info['description']}</p>
    </div>
    <div style="padding: 24px;">
      <table style="width: 100%; border-collapse: collapse;">
        <tr><td style="padding: 8px 0; font-weight: 600; width: 120px;">Brand:</td><td style="padding: 8px 0;">{brand_name} (@{brand_handle})</td></tr>
        <tr><td style="padding: 8px 0; font-weight: 600;">Target:</td><td style="padding: 8px 0;">{target}</td></tr>
        <tr><td style="padding: 8px 0; font-weight: 600;">Platform:</td><td style="padding: 8px 0;">{platform.title()}</td></tr>
        <tr><td style="padding: 8px 0; font-weight: 600;">Risk Score:</td><td style="padding: 8px 0;"><span style="background-color: {color}; color: white; padding: 2px 8px; border-radius: 4px; font-size: 14px;">{risk_score}/10 ({risk_level})</span></td></tr>
      </table>
      <h3 style="margin-top: 20px;">Evidence:</h3>
      <ul style="margin: 0; padding-left: 20px;">
"""
    for e in evidence[:5]:
        html += f'        <li style="margin: 4px 0;">{e}</li>\n'
    
    html += f"""      </ul>
      <div style="margin-top: 24px; padding: 16px; background-color: #f9fafb; border-radius: 8px;">
        <p style="margin: 0; font-weight: 600;">Recommended Action:</p>
"""
    if severity in ['critical', 'high']:
        html += """        <p style="margin: 8px 0 0;">File an abuse report immediately. Review takedown templates in the Brand Guard dashboard.</p>
"""
    else:
        html += """        <p style="margin: 8px 0 0;">Add to monitoring schedule. Review in weekly threat digest.</p>
"""
    if takedown_url:
        html += f"""        <a href="{takedown_url}" style="display: inline-block; margin-top: 12px; padding: 10px 20px; background-color: {color}; color: white; text-decoration: none; border-radius: 6px; font-weight: 600;">File Takedown Report</a>
"""
    
    html += f"""      </div>
    </div>
    <div style="background-color: #f9fafb; padding: 16px 24px; font-size: 12px; color: #6b7280; text-align: center;">
      Brand Guard by Jeeevs / AgenticBro — Scan first, trust later! 🔐<br>
      Educational purposes only. Not financial advice.
    </div>
  </div>
</body>
</html>"""
    
    return {
        'alert_id': f"alert-{int(datetime.now(timezone.utc).timestamp())}-{threat_type[:3]}",
        'generated_at': datetime.now(timezone.utc).isoformat(),
        'brand': {
            'name': brand_name,
            'handle': brand_handle,
        },
        'threat': {
            'type': threat_type,
            'severity': severity,
            'target': target,
            'platform': platform,
            'risk_score': risk_score,
            'risk_level': risk_level,
            'evidence': evidence,
        },
        'notification': {
            'subject': subject,
            'body_text': body,
            'body_html': html,
            'severity_info': severity_info,
        },
        'links': {
            'takedown_url': takedown_url,
            'dashboard_url': dashboard_url,
        },
        'disclaimer': 'Educational purposes only. Not financial advice. Not a guarantee of safety.',
    }


def main():
    parser = argparse.ArgumentParser(description='Alert Service — Brand Guard')
    parser.add_argument('--brand', required=True, help='Brand name')
    parser.add_argument('--handle', required=True, help='Brand handle')
    parser.add_argument('--threat-type', required=True,
                       choices=['impersonator', 'domain_lookalike', 'phone_scam', 'cross_channel', 'scammer_db', 'resolved'],
                       help='Type of threat')
    parser.add_argument('--severity', default='medium',
                       choices=['critical', 'high', 'medium', 'low'],
                       help='Alert severity')
    parser.add_argument('--target', required=True, help='Target (account, domain, phone)')
    parser.add_argument('--platform', default='unknown', help='Platform (x, instagram, etc.)')
    parser.add_argument('--risk-score', type=float, default=0, help='Risk score')
    parser.add_argument('--risk-level', default='MEDIUM',
                       choices=['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
                       help='Risk level')
    parser.add_argument('--evidence', nargs='*', default=[], help='Evidence items')
    parser.add_argument('--takedown-url', default='', help='URL to file takedown')
    parser.add_argument('--dashboard-url', default='', help='URL to Brand Guard dashboard')
    parser.add_argument('--json', action='store_true', help='Output as JSON')
    args = parser.parse_args()
    
    alert = generate_alert(
        brand_name=args.brand,
        brand_handle=args.handle,
        threat_type=args.threat_type,
        severity=args.severity,
        target=args.target,
        evidence=args.evidence,
        risk_score=args.risk_score,
        risk_level=args.risk_level,
        platform=args.platform,
        takedown_url=args.takedown_url,
        dashboard_url=args.dashboard_url,
    )
    
    if args.json:
        print(json.dumps(alert, indent=2))
    else:
        print(alert['notification']['body_text'])
    
    return 0


if __name__ == '__main__':
    sys.exit(main())