-- Durable Brand Guard queue, developer API access, and takedown lifecycle.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE brand_monitors ADD COLUMN IF NOT EXISTS next_scan_at TIMESTAMPTZ;
ALTER TABLE brand_monitors ADD COLUMN IF NOT EXISTS schedule_locked_until TIMESTAMPTZ;

-- Preserve the report generator's existing archive fields while linking reports
-- into the new submission lifecycle.
ALTER TABLE brand_guard_reports ADD COLUMN IF NOT EXISTS scan_id TEXT;
ALTER TABLE brand_guard_reports ADD COLUMN IF NOT EXISTS scan_type TEXT;
ALTER TABLE brand_guard_reports ADD COLUMN IF NOT EXISTS report_body TEXT;
ALTER TABLE brand_guard_reports ADD COLUMN IF NOT EXISTS missing_fields TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE brand_guard_reports ADD COLUMN IF NOT EXISTS confidence INTEGER;
CREATE INDEX IF NOT EXISTS idx_brand_guard_reports_scan_id ON brand_guard_reports(scan_id);

CREATE TABLE IF NOT EXISTS brand_guard_scan_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  api_key_id UUID,
  brand_monitor_id UUID REFERENCES brand_monitors(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL DEFAULT 'free' CHECK (plan_id IN ('free', 'guardian', 'sentinel', 'fortress')),
  job_type TEXT NOT NULL DEFAULT 'impersonator' CHECK (job_type IN ('impersonator', 'domain', 'email', 'full')),
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'leased', 'processing', 'completed', 'failed', 'canceled')),
  priority INTEGER NOT NULL DEFAULT 10,
  payload JSONB NOT NULL DEFAULT '{}',
  result JSONB,
  idempotency_key TEXT,
  scheduled_for TIMESTAMPTZ NOT NULL DEFAULT now(),
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  lease_token UUID,
  locked_by TEXT,
  locked_until TIMESTAMPTZ,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bg_queue_idempotency
  ON brand_guard_scan_queue(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_bg_queue_claim
  ON brand_guard_scan_queue(priority DESC, available_at, created_at)
  WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS idx_bg_queue_owner_created
  ON brand_guard_scan_queue(owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_monitors_next_scan
  ON brand_monitors(next_scan_at) WHERE is_active = true;

CREATE TABLE IF NOT EXISTS brand_guard_api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  key_prefix TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  scopes TEXT[] NOT NULL DEFAULT ARRAY['scans:read', 'scans:write'],
  rate_limit_per_minute INTEGER NOT NULL DEFAULT 60 CHECK (rate_limit_per_minute BETWEEN 1 AND 10000),
  last_used_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE brand_guard_scan_queue
  ADD CONSTRAINT brand_guard_scan_queue_api_key_id_fkey
  FOREIGN KEY (api_key_id) REFERENCES brand_guard_api_keys(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_bg_api_keys_owner ON brand_guard_api_keys(owner_id, created_at DESC);

CREATE TABLE IF NOT EXISTS brand_guard_api_usage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  api_key_id UUID REFERENCES brand_guard_api_keys(id) ON DELETE SET NULL,
  request_id UUID NOT NULL DEFAULT gen_random_uuid(),
  method TEXT NOT NULL,
  path TEXT NOT NULL,
  scope TEXT,
  status_code INTEGER NOT NULL,
  duration_ms INTEGER NOT NULL DEFAULT 0,
  units INTEGER NOT NULL DEFAULT 1,
  ip_hash TEXT,
  user_agent TEXT,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_usage_key_created ON brand_guard_api_usage_logs(api_key_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_usage_owner_created ON brand_guard_api_usage_logs(owner_id, created_at DESC);

CREATE TABLE IF NOT EXISTS brand_guard_api_rate_windows (
  api_key_id UUID NOT NULL REFERENCES brand_guard_api_keys(id) ON DELETE CASCADE,
  window_start TIMESTAMPTZ NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (api_key_id, window_start)
);

ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS brand_monitor_id UUID REFERENCES brand_monitors(id) ON DELETE CASCADE;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS report_id UUID REFERENCES brand_guard_reports(id) ON DELETE SET NULL;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS submission_provider TEXT;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS external_reference TEXT;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS submission_payload JSONB NOT NULL DEFAULT '{}';
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS provider_response JSONB;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 5;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS locked_by TEXT;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;
ALTER TABLE takedown_actions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE takedown_actions DROP CONSTRAINT IF EXISTS takedown_actions_status_check;
ALTER TABLE takedown_actions ADD CONSTRAINT takedown_actions_status_check CHECK (
  status IN ('draft', 'pending', 'queued', 'submitting', 'submitted', 'acknowledged', 'monitoring', 'removed', 'rejected', 'failed', 'canceled')
);

CREATE INDEX IF NOT EXISTS idx_takedown_claim
  ON takedown_actions(next_attempt_at, created_at)
  WHERE status IN ('queued', 'submitted', 'acknowledged', 'monitoring');
CREATE INDEX IF NOT EXISTS idx_takedown_owner_created ON takedown_actions(owner_id, created_at DESC);

CREATE OR REPLACE FUNCTION claim_takedown_actions(
  p_worker_id TEXT,
  p_limit INTEGER DEFAULT 5,
  p_lease_seconds INTEGER DEFAULT 120
) RETURNS SETOF takedown_actions
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
  WITH candidates AS (
    SELECT id FROM takedown_actions
    WHERE status IN ('queued', 'submitted', 'acknowledged', 'monitoring')
      AND COALESCE(next_attempt_at, now()) <= now()
      AND (locked_until IS NULL OR locked_until < now())
      AND attempt_count < max_attempts
    ORDER BY CASE status WHEN 'queued' THEN 0 ELSE 1 END, next_attempt_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(p_limit, 1), 25)
  )
  UPDATE takedown_actions t
  SET status = CASE WHEN t.status = 'queued' THEN 'submitting' ELSE t.status END,
      locked_by = p_worker_id, locked_until = now() + make_interval(secs => p_lease_seconds),
      updated_at = now()
  FROM candidates c WHERE t.id = c.id
  RETURNING t.*;
END;
$$;

CREATE OR REPLACE FUNCTION claim_brand_guard_scan_jobs(
  p_worker_id TEXT,
  p_limit INTEGER DEFAULT 1,
  p_lease_seconds INTEGER DEFAULT 120
) RETURNS SETOF brand_guard_scan_queue
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
  WITH candidates AS (
    SELECT id FROM brand_guard_scan_queue
    WHERE status = 'queued'
      AND available_at <= now()
      AND scheduled_for <= now()
      AND attempt_count < max_attempts
    ORDER BY priority DESC, available_at, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(p_limit, 1), 25)
  )
  UPDATE brand_guard_scan_queue q
  SET status = 'leased', locked_by = p_worker_id, lease_token = gen_random_uuid(),
      locked_until = now() + make_interval(secs => p_lease_seconds),
      attempt_count = attempt_count + 1, started_at = COALESCE(started_at, now()), updated_at = now()
  FROM candidates c WHERE q.id = c.id
  RETURNING q.*;
END;
$$;

CREATE OR REPLACE FUNCTION requeue_expired_brand_guard_jobs()
RETURNS INTEGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE affected INTEGER;
BEGIN
  UPDATE brand_guard_scan_queue
  SET status = CASE WHEN attempt_count >= max_attempts THEN 'failed' ELSE 'queued' END,
      available_at = CASE WHEN attempt_count >= max_attempts THEN available_at ELSE now() + interval '1 minute' END,
      locked_by = NULL, lease_token = NULL, locked_until = NULL,
      last_error = COALESCE(last_error, 'Worker lease expired'), updated_at = now()
  WHERE locked_until < now()
    AND (status = 'leased' OR (status = 'processing' AND COALESCE(result->>'scan_id', '') = ''));
  GET DIAGNOSTICS affected = ROW_COUNT;
  RETURN affected;
END;
$$;

CREATE OR REPLACE FUNCTION consume_brand_guard_rate_limit(p_api_key_id UUID, p_limit INTEGER)
RETURNS TABLE(allowed BOOLEAN, remaining INTEGER, reset_at TIMESTAMPTZ)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE current_window TIMESTAMPTZ := date_trunc('minute', now());
DECLARE current_count INTEGER;
BEGIN
  INSERT INTO brand_guard_api_rate_windows(api_key_id, window_start, request_count)
  VALUES (p_api_key_id, current_window, 1)
  ON CONFLICT (api_key_id, window_start)
  DO UPDATE SET request_count = brand_guard_api_rate_windows.request_count + 1
  RETURNING request_count INTO current_count;
  RETURN QUERY SELECT current_count <= p_limit, GREATEST(p_limit - current_count, 0), current_window + interval '1 minute';
END;
$$;

ALTER TABLE brand_guard_scan_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_api_usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_api_rate_windows ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners read scan queue" ON brand_guard_scan_queue FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read API keys" ON brand_guard_api_keys FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners create API keys" ON brand_guard_api_keys FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owners update API keys" ON brand_guard_api_keys FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Owners read API usage" ON brand_guard_api_usage_logs FOR SELECT USING (auth.uid() = owner_id);

GRANT EXECUTE ON FUNCTION claim_brand_guard_scan_jobs(TEXT, INTEGER, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION requeue_expired_brand_guard_jobs() TO service_role;
GRANT EXECUTE ON FUNCTION consume_brand_guard_rate_limit(UUID, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION claim_takedown_actions(TEXT, INTEGER, INTEGER) TO service_role;
