-- Premium Brand Guard threat intelligence: DNS transitions, DMARC, sandbox jobs, and audit logs.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE brand_monitors ADD COLUMN IF NOT EXISTS dmarc_rua_token TEXT UNIQUE;
ALTER TABLE brand_monitors ADD COLUMN IF NOT EXISTS domain_watch_next_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE brand_monitors ADD COLUMN IF NOT EXISTS domain_watch_locked_until TIMESTAMPTZ;
UPDATE brand_monitors SET dmarc_rua_token = encode(gen_random_bytes(16), 'hex') WHERE dmarc_rua_token IS NULL;
ALTER TABLE brand_monitors ALTER COLUMN dmarc_rua_token SET DEFAULT encode(gen_random_bytes(16), 'hex');
ALTER TABLE brand_monitors ALTER COLUMN dmarc_rua_token SET NOT NULL;

CREATE TABLE IF NOT EXISTS brand_guard_detected_threats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  brand_monitor_id UUID NOT NULL REFERENCES brand_monitors(id) ON DELETE CASCADE,
  threat_type TEXT NOT NULL CHECK (threat_type IN ('lookalike', 'spoofing', 'phishing_kit')),
  target TEXT NOT NULL,
  resolved_ips TEXT[] NOT NULL DEFAULT '{}',
  mx_records TEXT[] NOT NULL DEFAULT '{}',
  phishing_kit_fingerprint TEXT,
  exfil_endpoints TEXT[] NOT NULL DEFAULT '{}',
  confidence NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (confidence BETWEEN 0 AND 100),
  severity INTEGER NOT NULL DEFAULT 1 CHECK (severity BETWEEN 1 AND 5),
  status TEXT NOT NULL DEFAULT 'detected' CHECK (status IN ('detected', 'analyzing', 'pending_review', 'takedown_submitted', 'resolved', 'false_positive')),
  evidence JSONB NOT NULL DEFAULT '{}',
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_mutated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (brand_monitor_id, threat_type, target)
);

CREATE INDEX IF NOT EXISTS idx_bg_threats_owner ON brand_guard_detected_threats(owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_threats_brand ON brand_guard_detected_threats(brand_monitor_id, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_threats_target ON brand_guard_detected_threats(target);
CREATE INDEX IF NOT EXISTS idx_bg_threats_status ON brand_guard_detected_threats(status, severity DESC);

CREATE TABLE IF NOT EXISTS brand_guard_dns_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_monitor_id UUID NOT NULL REFERENCES brand_monitors(id) ON DELETE CASCADE,
  domain TEXT NOT NULL,
  resolves BOOLEAN NOT NULL,
  ip_addresses TEXT[] NOT NULL DEFAULT '{}',
  mx_records TEXT[] NOT NULL DEFAULT '{}',
  checked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bg_dns_observation_latest ON brand_guard_dns_observations(brand_monitor_id, domain, checked_at DESC);

CREATE TABLE IF NOT EXISTS brand_guard_dmarc_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  brand_monitor_id UUID NOT NULL REFERENCES brand_monitors(id) ON DELETE CASCADE,
  report_id TEXT NOT NULL,
  reporter TEXT,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  source_filename TEXT,
  message_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  raw_size_bytes INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (brand_monitor_id, report_id)
);
CREATE INDEX IF NOT EXISTS idx_bg_dmarc_reports_owner ON brand_guard_dmarc_reports(owner_id, period_end DESC);

CREATE TABLE IF NOT EXISTS brand_guard_dmarc_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id UUID NOT NULL REFERENCES brand_guard_dmarc_reports(id) ON DELETE CASCADE,
  brand_monitor_id UUID NOT NULL REFERENCES brand_monitors(id) ON DELETE CASCADE,
  source_ip INET NOT NULL,
  message_count INTEGER NOT NULL,
  dkim_result TEXT,
  spf_result TEXT,
  disposition TEXT,
  unauthorized BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bg_dmarc_sources_brand ON brand_guard_dmarc_sources(brand_monitor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_dmarc_sources_ip ON brand_guard_dmarc_sources(source_ip);

CREATE TABLE IF NOT EXISTS brand_guard_threat_intel_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  threat_id UUID NOT NULL REFERENCES brand_guard_detected_threats(id) ON DELETE CASCADE,
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  target_url TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'leased', 'running', 'completed', 'failed', 'canceled')),
  result JSONB,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts BETWEEN 1 AND 5),
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  locked_by TEXT,
  locked_until TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (threat_id)
);
CREATE INDEX IF NOT EXISTS idx_bg_intel_claim ON brand_guard_threat_intel_jobs(available_at, created_at) WHERE status = 'queued';

CREATE OR REPLACE FUNCTION enqueue_high_confidence_threat_intel()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.threat_type IN ('lookalike', 'phishing_kit') AND NEW.confidence >= 85 AND NEW.status NOT IN ('resolved', 'false_positive') THEN
    INSERT INTO brand_guard_threat_intel_jobs(threat_id, owner_id, target_url)
    VALUES (NEW.id, NEW.owner_id, CASE WHEN NEW.target ~ '^https://' THEN NEW.target ELSE 'https://' || NEW.target END)
    ON CONFLICT (threat_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enqueue_high_confidence_threat_intel ON brand_guard_detected_threats;
CREATE TRIGGER trg_enqueue_high_confidence_threat_intel
AFTER INSERT OR UPDATE OF confidence, status ON brand_guard_detected_threats
FOR EACH ROW EXECUTE FUNCTION enqueue_high_confidence_threat_intel();

CREATE TABLE IF NOT EXISTS brand_guard_takedown_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  threat_id UUID NOT NULL REFERENCES brand_guard_detected_threats(id) ON DELETE CASCADE,
  action_id UUID REFERENCES takedown_actions(id) ON DELETE SET NULL,
  provider_name TEXT NOT NULL,
  submission_channel TEXT NOT NULL CHECK (submission_channel IN ('api', 'email')),
  payload_sent JSONB NOT NULL DEFAULT '{}',
  provider_ticket_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'pending', 'acknowledged', 'rejected', 'success', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bg_takedown_logs_threat ON brand_guard_takedown_logs(threat_id, created_at DESC);

CREATE OR REPLACE FUNCTION claim_domain_watch_brands(p_worker_id TEXT, p_limit INTEGER DEFAULT 2, p_lease_seconds INTEGER DEFAULT 300)
RETURNS SETOF brand_monitors LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY WITH candidates AS (
    SELECT id FROM brand_monitors
    WHERE is_active = true AND brand_domain IS NOT NULL
      AND COALESCE(domain_watch_next_at, now()) <= now()
      AND (domain_watch_locked_until IS NULL OR domain_watch_locked_until < now())
    ORDER BY domain_watch_next_at NULLS FIRST FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(p_limit, 1), 10)
  ) UPDATE brand_monitors b
    SET domain_watch_locked_until = now() + make_interval(secs => p_lease_seconds), updated_at = now()
    FROM candidates c WHERE b.id = c.id RETURNING b.*;
END;
$$;

CREATE OR REPLACE FUNCTION claim_threat_intel_jobs(p_worker_id TEXT, p_limit INTEGER DEFAULT 1, p_lease_seconds INTEGER DEFAULT 300)
RETURNS SETOF brand_guard_threat_intel_jobs LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY WITH candidates AS (
    SELECT id FROM brand_guard_threat_intel_jobs
    WHERE status = 'queued' AND available_at <= now() AND attempt_count < max_attempts
      AND (locked_until IS NULL OR locked_until < now())
    ORDER BY available_at, created_at FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(p_limit, 1), 4)
  ) UPDATE brand_guard_threat_intel_jobs j
    SET status = 'leased', locked_by = p_worker_id,
        locked_until = now() + make_interval(secs => p_lease_seconds),
        attempt_count = attempt_count + 1, updated_at = now()
    FROM candidates c WHERE j.id = c.id RETURNING j.*;
END;
$$;

ALTER TABLE brand_guard_detected_threats ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_dns_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_dmarc_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_dmarc_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_threat_intel_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_takedown_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners read threats" ON brand_guard_detected_threats FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read DNS observations" ON brand_guard_dns_observations FOR SELECT USING (brand_monitor_id IN (SELECT id FROM brand_monitors WHERE owner_id = auth.uid()));
CREATE POLICY "Owners read DMARC reports" ON brand_guard_dmarc_reports FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read DMARC sources" ON brand_guard_dmarc_sources FOR SELECT USING (brand_monitor_id IN (SELECT id FROM brand_monitors WHERE owner_id = auth.uid()));
CREATE POLICY "Owners read intel jobs" ON brand_guard_threat_intel_jobs FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read takedown logs" ON brand_guard_takedown_logs FOR SELECT USING (threat_id IN (SELECT id FROM brand_guard_detected_threats WHERE owner_id = auth.uid()));

GRANT EXECUTE ON FUNCTION claim_domain_watch_brands(TEXT, INTEGER, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION claim_threat_intel_jobs(TEXT, INTEGER, INTEGER) TO service_role;
