-- Brand Guard customer delivery, enterprise SLA, reporting, and account management.

CREATE TABLE IF NOT EXISTS brand_guard_delivery_endpoints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  brand_monitor_id UUID REFERENCES brand_monitors(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  channel TEXT NOT NULL CHECK (channel IN ('slack', 'webhook')),
  endpoint_ciphertext TEXT NOT NULL,
  signing_secret_ciphertext TEXT,
  event_types TEXT[] NOT NULL DEFAULT ARRAY['alert'],
  minimum_severity TEXT NOT NULL DEFAULT 'low' CHECK (minimum_severity IN ('info', 'low', 'medium', 'high', 'critical')),
  enabled BOOLEAN NOT NULL DEFAULT true,
  last_success_at TIMESTAMPTZ,
  last_failure_at TIMESTAMPTZ,
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_delivery_endpoints_owner ON brand_guard_delivery_endpoints(owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_delivery_endpoints_monitor ON brand_guard_delivery_endpoints(brand_monitor_id) WHERE enabled = true;

CREATE TABLE IF NOT EXISTS brand_guard_delivery_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint_id UUID NOT NULL REFERENCES brand_guard_delivery_endpoints(id) ON DELETE CASCADE,
  alert_id UUID REFERENCES brand_guard_alerts(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL DEFAULT 'alert',
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'leased', 'delivered', 'dead_letter', 'canceled')),
  idempotency_key TEXT NOT NULL UNIQUE,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 8,
  available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  lease_token UUID,
  locked_by TEXT,
  locked_until TIMESTAMPTZ,
  last_error TEXT,
  last_status_code INTEGER,
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_delivery_claim ON brand_guard_delivery_jobs(available_at, created_at) WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS idx_bg_delivery_owner ON brand_guard_delivery_jobs(owner_id, created_at DESC);

CREATE TABLE IF NOT EXISTS brand_guard_delivery_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES brand_guard_delivery_jobs(id) ON DELETE CASCADE,
  endpoint_id UUID REFERENCES brand_guard_delivery_endpoints(id) ON DELETE SET NULL,
  attempt_number INTEGER NOT NULL,
  status_code INTEGER,
  duration_ms INTEGER NOT NULL,
  error TEXT,
  response_excerpt TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_delivery_attempts_job ON brand_guard_delivery_attempts(job_id, created_at DESC);

CREATE TABLE IF NOT EXISTS brand_guard_delivery_dead_letters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  original_job_id UUID NOT NULL UNIQUE REFERENCES brand_guard_delivery_jobs(id) ON DELETE CASCADE,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  endpoint_id UUID REFERENCES brand_guard_delivery_endpoints(id) ON DELETE SET NULL,
  payload JSONB NOT NULL,
  final_error TEXT,
  attempt_count INTEGER NOT NULL,
  resolved_at TIMESTAMPTZ,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_dead_letters_unresolved ON brand_guard_delivery_dead_letters(created_at DESC) WHERE resolved_at IS NULL;

CREATE TABLE IF NOT EXISTS brand_guard_sla_policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  plan_id TEXT NOT NULL DEFAULT 'fortress',
  availability_target NUMERIC(5,3) NOT NULL DEFAULT 99.900,
  critical_ack_minutes INTEGER NOT NULL DEFAULT 15,
  high_ack_minutes INTEGER NOT NULL DEFAULT 60,
  report_due_day INTEGER NOT NULL DEFAULT 1 CHECK (report_due_day BETWEEN 0 AND 6),
  escalation_email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS brand_guard_enterprise_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_type TEXT NOT NULL CHECK (report_type IN ('weekly_briefing', 'monthly_sla', 'custom')),
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('generating', 'ready', 'delivered', 'failed')),
  summary JSONB NOT NULL DEFAULT '{}',
  report_markdown TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_enterprise_reports_owner ON brand_guard_enterprise_reports(owner_id, period_end DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bg_enterprise_reports_period ON brand_guard_enterprise_reports(owner_id, report_type, period_start, period_end);

CREATE TABLE IF NOT EXISTS brand_guard_account_managers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT true,
  max_accounts INTEGER NOT NULL DEFAULT 25,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS brand_guard_account_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  manager_id UUID NOT NULL REFERENCES brand_guard_account_managers(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'ended')),
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  next_review_at TIMESTAMPTZ,
  notes TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS brand_guard_account_cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assignment_id UUID REFERENCES brand_guard_account_assignments(id) ON DELETE SET NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  subject TEXT NOT NULL,
  description TEXT,
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'waiting_customer', 'resolved', 'closed')),
  due_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bg_account_cases_owner ON brand_guard_account_cases(owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bg_account_cases_open ON brand_guard_account_cases(priority DESC, created_at) WHERE status IN ('open', 'in_progress');

CREATE TABLE IF NOT EXISTS brand_guard_account_case_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id UUID NOT NULL REFERENCES brand_guard_account_cases(id) ON DELETE CASCADE,
  actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  message TEXT,
  metadata JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION claim_brand_guard_delivery_jobs(
  p_worker_id TEXT, p_limit INTEGER DEFAULT 10, p_lease_seconds INTEGER DEFAULT 60
) RETURNS SETOF brand_guard_delivery_jobs
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  RETURN QUERY
  WITH candidates AS (
    SELECT id FROM brand_guard_delivery_jobs
    WHERE status = 'queued' AND available_at <= now() AND attempt_count < max_attempts
    ORDER BY available_at, created_at FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(p_limit, 1), 50)
  )
  UPDATE brand_guard_delivery_jobs j
  SET status = 'leased', locked_by = p_worker_id, lease_token = gen_random_uuid(),
      locked_until = now() + make_interval(secs => p_lease_seconds), updated_at = now()
  FROM candidates c WHERE j.id = c.id RETURNING j.*;
END;
$$;

CREATE OR REPLACE FUNCTION enqueue_brand_guard_alert_deliveries()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO brand_guard_delivery_jobs(owner_id, endpoint_id, alert_id, event_type, payload, idempotency_key)
  SELECT m.owner_id, e.id, NEW.id, 'alert', jsonb_build_object(
    'event', 'brand_guard.alert', 'alert_id', NEW.id, 'brand_monitor_id', NEW.brand_monitor_id,
    'severity', NEW.severity, 'title', NEW.title, 'message', NEW.message,
    'platform', NEW.platform, 'risk_score', NEW.risk_score, 'risk_level', NEW.risk_level,
    'evidence', NEW.evidence, 'created_at', NEW.created_at
  ), 'alert:' || NEW.id::text || ':' || e.id::text
  FROM brand_monitors m JOIN brand_guard_delivery_endpoints e ON e.owner_id = m.owner_id
  WHERE m.id = NEW.brand_monitor_id AND e.enabled = true
    AND (e.brand_monitor_id IS NULL OR e.brand_monitor_id = NEW.brand_monitor_id)
    AND 'alert' = ANY(e.event_types)
    AND CASE NEW.severity WHEN 'critical' THEN 5 WHEN 'high' THEN 4 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 ELSE 1 END
      >= CASE e.minimum_severity WHEN 'critical' THEN 5 WHEN 'high' THEN 4 WHEN 'medium' THEN 3 WHEN 'low' THEN 2 ELSE 1 END
  ON CONFLICT (idempotency_key) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enqueue_brand_guard_alert_deliveries ON brand_guard_alerts;
CREATE TRIGGER trg_enqueue_brand_guard_alert_deliveries AFTER INSERT ON brand_guard_alerts
FOR EACH ROW EXECUTE FUNCTION enqueue_brand_guard_alert_deliveries();

ALTER TABLE brand_guard_delivery_endpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_delivery_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_delivery_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_delivery_dead_letters ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_sla_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_enterprise_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_account_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_account_managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_account_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_guard_account_case_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners manage delivery endpoints" ON brand_guard_delivery_endpoints FOR ALL USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owners read delivery jobs" ON brand_guard_delivery_jobs FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read delivery attempts" ON brand_guard_delivery_attempts FOR SELECT USING (job_id IN (SELECT id FROM brand_guard_delivery_jobs WHERE owner_id = auth.uid()));
CREATE POLICY "Owners read dead letters" ON brand_guard_delivery_dead_letters FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read SLA" ON brand_guard_sla_policies FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read enterprise reports" ON brand_guard_enterprise_reports FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read account assignment" ON brand_guard_account_assignments FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Owners read assigned manager" ON brand_guard_account_managers FOR SELECT USING (id IN (SELECT manager_id FROM brand_guard_account_assignments WHERE owner_id = auth.uid()));
CREATE POLICY "Owners manage account cases" ON brand_guard_account_cases FOR ALL USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Owners read case events" ON brand_guard_account_case_events FOR SELECT USING (case_id IN (SELECT id FROM brand_guard_account_cases WHERE owner_id = auth.uid()));

GRANT EXECUTE ON FUNCTION claim_brand_guard_delivery_jobs(TEXT, INTEGER, INTEGER) TO service_role;
